name: .NET Tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --logger "trx;LogFileName=TestResults.xml"

      - name: Publish Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: "**/TestResults"

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure() # run this step even if previous step failed
        with:
          artifact: TestResults
          name: .NET Tests
          path: LocalVenue.Tests\TestResults\TestResults.xml
          reporter: dotnet-trx
